### ISSUE TITLE
[Proposal] Create a checklist template/checklist for reviewing design pull-requests

### ISSUE THREAD

**Issue by nickttng** [18F/product-design#11]
**Why:** As a product designer reviewing PRs, I would like a template/checklist when reviewing design PRs, so I don't have to continually evaluate off the top of my head. The template/checklist can also be a tool for non-designers to refer from when they review PRs (Connecting inclusive design principles to daily practices). 

Few scenario examples to built around simple, "Have we done this?" questions:

**Scenario 1:** When reviewing a design pattern
1. Ensure that the design pattern is accessible / inclusive
2. Ensure that it adapts well in various responsive widths
3. Analyze how it can be abused (or attacked)

**Scenario 2:** Review a content written in Markdown
1. To ensure that Markdown syntax, e.g. headings, is used correctly (Example: No double #/H1 per page, which is a common mistake I've seen often here at 18F/TTS)
2. Ensure that Markdown images have alt tag
3. Ask, "have we studied and understood possible sources of bias in our content?"

**How:**
- [ ] Have a discussion whether this proposal is worth an effort
  - [ ] If it is worth an effort, ask ourselves how do we proceed next? 🤔
  - [ ] If it is worth an effort, but not at the moment, ask ourselves when should we revisit at a better time ⏳
  - [ ] If it is _not_ worth an effort at all, shelf it 💀

**AC**
- [ ] To be determined by discussion(s)
